controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

not_found:
    path: /404
    controller: App\Controller\ExceptionController::notFound

catch_all:
    path: /{url}
    controller: App\Controller\ExceptionController::notFound
    requirements:
        url: .*

